#!/usr/bin/env bash

set -e -o pipefail

if GIT_TOP=$(git rev-parse --show-toplevel 2>/dev/null) && echo "$GIT_TOP" | grep -iq "clickhouse"; then
  ROOT_PATH="$GIT_TOP"
else
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  ROOT_PATH="$(realpath "$SCRIPT_DIR/../")"
fi
IFS=$'\t'

echo "// autogenerated by $0"
echo "const char * library_licenses[] = {"
${ROOT_PATH}/utils/list-licenses/list-licenses.sh | while read row; do
    arr=($row)

    echo "\"${arr[0]}\", \"${arr[1]}\", \"${arr[2]}\", R\"heredoc($(cat "${ROOT_PATH}/${arr[2]}"))heredoc\","
    echo
done
echo "nullptr"
echo "};"
